"""Generate the pygbag index.html template used by this project.

Run this to regenerate ``tools/piu.tmpl`` from pygbag's stock template:

    python tools/make_template.py

The result is committed, so builds do not depend on this script or on the CDN
being reachable at build time. Re-run it when the pinned pygbag version
changes, then review the diff.

Two changes are applied to the stock template:

1. **Boot diagnostics are inlined** ahead of pygbag's loader, so ``fetch`` and
   ``XMLHttpRequest`` are wrapped before anything uses them. A bare
   "Failed to fetch" carries no URL; the wrappers attach one.

2. **browserfs.min.js is loaded defensively.** The stock template emits
   ``{cdn}/browserfs.min.js`` while ``cdn`` already ends in a slash, producing
   a doubled slash - and the file is absent from the 0.9.3 CDN under either
   spelling. A plain script tag for a missing file logs a console error and
   leaves no trace in the page, so it is replaced with a tag that reports its
   own failure through the diagnostics log.
"""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

PYGBAG_VERSION = "0.9.3"
CDN = f"https://pygame-web.github.io/cdn/{PYGBAG_VERSION}/"
STOCK_TEMPLATE = CDN + "default.tmpl"

HERE = Path(__file__).resolve().parent
OUTPUT = HERE / "piu.tmpl"

#: Inlined in order. Diagnostics must come first so the later scripts can log
#: through it, and all of them must precede pygbag's loader.
INLINE_SCRIPTS = (
    HERE / "boot_diagnostics.js",
    HERE / "web_audio.js",
)

# The stock line that mis-joins the CDN root with a leading slash.
BROWSERFS_STOCK = '<script src="{{cookiecutter.cdn}}/browserfs.min.js"></script>'

BROWSERFS_PATCHED = """<!-- browserfs is optional and is absent from the pygbag """ + PYGBAG_VERSION + """ CDN.
     Loaded without the stock template's doubled slash, and with explicit
     success/failure reporting so its absence is visible rather than silent. -->
<script>
(function () {
  var src = "{{cookiecutter.cdn}}browserfs.min.js";
  var s = document.createElement("script");
  s.src = src;
  s.async = false;
  s.onerror = function () {
    if (window.piuBootLog) {
      window.piuBootLog("WARN", "optional browserfs.min.js unavailable: " + src);
      window.piuBootLog("HINT", "Known gap in the pygbag """ + PYGBAG_VERSION + """ CDN. Not fatal.");
    }
  };
  s.onload = function () {
    if (window.piuBootLog) window.piuBootLog("OK", "browserfs.min.js loaded");
  };
  document.head.appendChild(s);
})();
</script>"""

MARKER = "<html lang=\"en-us\">"


def fetch_stock() -> str:
    print(f"fetching {STOCK_TEMPLATE}")
    with urllib.request.urlopen(STOCK_TEMPLATE, timeout=60) as response:
        return response.read().decode("utf-8")


def build(stock: str) -> str:
    if MARKER not in stock:
        raise SystemExit(
            "stock template no longer starts with {!r}; inspect it before "
            "regenerating".format(MARKER)
        )

    # Insert our scripts immediately after the opening <html>, which puts them
    # ahead of the pygbag loader script that follows on the same line. Order
    # matters: the fetch wrapper has to be installed before anything fetches,
    # and the audio bridge logs through the diagnostics panel.
    blocks = [MARKER, "\n"]
    for path in INLINE_SCRIPTS:
        blocks.append(
            "<!-- piu: {name} - generated by tools/make_template.py.\n"
            "     Edit tools/{name} and regenerate; do not edit here. -->\n"
            "<script>\n{body}\n</script>\n".format(
                name=path.name, body=path.read_text(encoding="utf-8")
            )
        )
    patched = stock.replace(MARKER, "".join(blocks), 1)

    if BROWSERFS_STOCK not in patched:
        print(
            "WARNING: the browserfs line was not found; upstream may have "
            "fixed it. Skipping that patch.",
            file=sys.stderr,
        )
    else:
        patched = patched.replace(BROWSERFS_STOCK, BROWSERFS_PATCHED, 1)

    return patched


def main() -> None:
    missing = [str(p) for p in INLINE_SCRIPTS if not p.is_file()]
    if missing:
        raise SystemExit("missing: " + ", ".join(missing))

    result = build(fetch_stock())
    OUTPUT.write_text(result, encoding="utf-8")

    for path in INLINE_SCRIPTS:
        print(f"  inlined {path.name} ({path.stat().st_size:,} bytes)")
    print(f"wrote {OUTPUT}  ({len(result):,} bytes)")
    print("Build with:  python -m pygbag --template tools/piu.tmpl --build main.py")


if __name__ == "__main__":
    main()
