"""Capture the stdlib that pygbag's CPython actually ships.

Run this to regenerate ``tests/fixtures/pygbag_stdlib.txt``:

    python tools/probe_stdlib.py

Why this exists
---------------
pygbag ships a trimmed CPython. Modules that are unremarkable on the desktop
are simply absent in the browser, and the failure arrives as a
``ModuleNotFoundError`` at the moment the module is first imported - which for
a lazily-imported screen can be long after boot, in front of a player.

``statistics`` was the case that prompted this: pure-python, utterly ordinary,
and not shipped. Testing locally could never have caught it, because the
desktop interpreter has everything.

How it works
------------
The Emscripten loader ``cpython312/main.js`` embeds the manifest of every file
packaged into ``main.data``, including each stdlib ``.py`` path. That manifest
is the authoritative answer for anything shipped as source.

It has one blind spot: modules that are builtin C extensions or frozen into
the interpreter never appear as files. ``math``, ``sys`` and ``abc`` are all
absent from the manifest yet perfectly importable. Those are listed separately
in ``ALWAYS_AVAILABLE`` below, which is curated by hand and deliberately
conservative - it is better to be asked about a new import than to ship a
module that is not there.
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

PYGBAG_VERSION = "0.9.3"
PYTHON_TAG = "cpython312"
PYTHON_VERSION = "3.12"
MANIFEST_URL = (
    f"https://pygame-web.github.io/cdn/{PYGBAG_VERSION}/{PYTHON_TAG}/main.js"
)

OUTPUT = Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "pygbag_stdlib.txt"

#: Builtin or frozen modules. These are compiled into the interpreter rather
#: than shipped as files, so they never appear in the manifest even though they
#: import fine. Verified against a running browser build before being added -
#: do not add to this list on the assumption that something "must" be present.
ALWAYS_AVAILABLE = {
    "__future__",
    "_abc",
    "abc",
    "array",
    "atexit",
    "binascii",
    "builtins",
    "cmath",
    "errno",
    "gc",
    "io",
    "itertools",
    "marshal",
    "math",
    "operator",
    "posix",
    "select",
    "struct",
    "sys",
    "time",
    "unicodedata",
    "zlib",
}

#: Provided by the pygbag runtime rather than by CPython.
RUNTIME_PROVIDED = {"platform", "embed", "aio", "pygame"}


def fetch_manifest() -> str:
    print(f"fetching {MANIFEST_URL}")
    with urllib.request.urlopen(MANIFEST_URL, timeout=120) as response:
        return response.read().decode("utf-8", "replace")


def shipped_modules(manifest: str) -> set[str]:
    """Top-level module and package names packaged as stdlib source."""
    pattern = r"/lib/python" + re.escape(PYTHON_VERSION) + r"/([^\"',\s]+)"
    modules: set[str] = set()
    for path in re.findall(pattern, manifest):
        head = path.split("/")[0]
        if head.startswith("__pycache__") or not head:
            continue
        modules.add(head[:-3] if head.endswith(".py") else head)
    return modules


def main() -> None:
    shipped = shipped_modules(fetch_manifest())
    if len(shipped) < 50:
        raise SystemExit(
            "only {} modules found - the manifest format probably changed; "
            "inspect main.js before trusting this".format(len(shipped))
        )

    available = sorted(shipped | ALWAYS_AVAILABLE | RUNTIME_PROVIDED)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(
        "# Modules importable in the pygbag {} / CPython {} browser runtime.\n"
        "# Generated by tools/probe_stdlib.py - do not edit by hand.\n"
        "# {} packaged as stdlib source, plus {} builtin/frozen and {} "
        "runtime-provided.\n".format(
            PYGBAG_VERSION, PYTHON_VERSION,
            len(shipped), len(ALWAYS_AVAILABLE), len(RUNTIME_PROVIDED),
        )
        + "\n".join(available)
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUTPUT} ({len(available)} modules)")

    notable = ["statistics", "math", "decimal", "fractions", "typing", "bisect"]
    for name in notable:
        print(f"  {name:<12}: {'yes' if name in available else 'NO'}")


if __name__ == "__main__":
    main()
